---
abstract: 'horizontal/vertical progress bars for Tickit'
author:
  - 'Tom Molesworth <cpan@entitymodel.com>'
build_requires:
  Capture::Tiny: 0
  Test::CheckDeps: 0.006
  Test::More: 0.98
  blib: 0
  perl: 5.010001
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300036, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tickit-Widget-Progressbar
requires:
  Tickit: 0.33
  parent: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Tickit-Widget-Progressbar
  homepage: http://search.cpan.org/dist/Tickit-Widget-Progressbar/
version: 0.100
